# Read once by Hatch.run; -log FILE adds a file handler for errors.

# Default global logging level
.level=INFO

handlers=java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level=FINE
java.util.logging.ConsoleHandler.formatter = edu.stonybrook.bmi.hatch.SingleLineFormatter

edu.stonybrook.bmi.hatch.Hatch.level=FINE
